#!/bin/sh

case "$1" in
    start)
        echo "Loading LDD modules"
        modprobe hello
        modprobe faulty
        modprobe scull
        ;;
    stop)
        echo "Unloading LDD modules"
        rmmod scull
        rmmod faulty
        rmmod hello
        ;;
    *)
        exit 1
        ;;
esac

exit 0
